version: "3.8"
services:
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "goevent"
      MYSQL_USER: "goevent"
      MYSQL_PASSWORD: "abc123"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    restart: unless-stopped
    volumes:
      - "appmysql:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
volumes:
  appmysql:
    driver: local
